### PR TITLE
css-canvas-medical | Lucca Rizzi

### PR DESCRIPTION
**Pull request by luccarizzi**
Screen Shot 2020-11-14 at 1 36 29 PM
Screen Shot 2020-11-14 at 1 36 46 PM
Screen Shot 2020-11-14 at 1 36 55 PM

### CODE REVIEW

**Review by Zhiwutian — APPROVED** [review]
👍

**Comment by luccarizzi** [comment]
index.html

index

**Comment by luccarizzi** [comment]
product.html

product

**Comment by luccarizzi** [comment]
implementation.html

implementation

**Comment by luccarizzi** [comment]
about-us.html

about-us

**Comment by luccarizzi** [comment]
blog.html

blog

**Comment by luccarizzi** [comment]
contact-us.html

contact-us

**Pull request merged**
