### PR TITLE
css-four-column-layout | Lucca Rizzi

### PR DESCRIPTION
**Pull request by luccarizzi**
Screen Shot 2020-11-17 at 8 05 20 PM

### CODE REVIEW

**Review by Zhiwutian — CHANGES_REQUESTED** [review]
Hey Lucca, the only change needed I see is to reduce the distance between the h3 and the p tag text content below the images. Looking great!

**Review by Zhiwutian — APPROVED** [review]
👍

**Comment by luccarizzi** [comment]
Screen Shot 2020-11-18 at 12 00 13 PM

**Pull request merged**
